[book]
authors = ["Cairo-by-Practice community"]
language = "en"
multilingual = false
src = "src"
title = "Cairo by Practice"

[build]
extra-watch-dirs = ["po"]

[preprocessor.cairo]
after = ["links"]

[preprocessor.gettext]
after = ["cairo"]


[output.html]
git-repository-url = "https://github.com/cairo-by-practice/cairo-by-practice.github.io/"
edit-url-template = "https://github.com/cairo-by-practice/cairo-by-practice.github.io/edit/main/{path}"
playground.runnable = true
playground.editable = true
